### ISSUE TITLE
Schedule does not show

### ISSUE THREAD

**Issue by mklaehn** [TweetWallFX/TweetwallFX-Devoxx-2019-UA#18]
**Describe the bug**
The schedule is not show due to a parsing error of the timeslots from an to times.

**To Reproduce**
Set jvmArgs to day and time where schedule is available and start the cinema project.
Exception will appear in output:
```
2019-10-31 21:12:51,929 FATAL [JavaFX Application Thread] api.StepEngine (StepEngine.java:250) - StepExecution has terminal failure Devoxx19ShowSchedule 
2019-10-31 21:12:51,929 FATAL [JavaFX Application Thread] api.StepEngine (StepEngine.java:251) - caused by
java.time.format.DateTimeParseException: Text '2019-11-01T09:30:00ZZ' could not be parsed at index 2
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2049) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1951) ~[?:?]
	at java.time.OffsetTime.parse(OffsetTime.java:327) ~[?:?]
	at java.time.OffsetTime.parse(OffsetTime.java:312) ~[?:?]
	at org.tweetwallfx.devoxx.cfp.stepengine.dataprovider.SessionData.lambda$from$1(SessionData.java:76) ~[tweetwallfx-devoxx-cfp-stepengine-1.1.1.jar:1.1.1]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.tweetwallfx.devoxx.cfp.stepengine.dataprovider.SessionData.from(SessionData.java:77) ~[tweetwallfx-devoxx-cfp-stepengine-1.1.1.jar:1.1.1]
	at org.tweetwallfx.devoxx.cfp.stepengine.dataprovider.ScheduleDataProvider.getFilteredSessionData(ScheduleDataProvider.java:79) ~[tweetwallfx-devoxx-cfp-stepengine-1.1.1.jar:1.1.1]
	at org.tweetwallfx.devoxx19ua.steps.Devoxx19ShowSchedule.doStep(Devoxx19ShowSchedule.java:84) ~[tweetwallfx-devoxx-2019-ua-stepengine-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at org.tweetwallfx.stepengine.api.StepEngine.lambda$process$13(StepEngine.java:248) ~[tweetwallfx-stepengine-api-1.1.1.jar:1.1.1]
```

**Expected behavior**
No exception raised and schedule shown.

**Comment by mklaehn** [comment]
The ScheduleSlot expects HH:MM only instead of ISO DateTime.
Also a room setup is expected for sorting the rooms according to their setup (cinema rooms and BOF rooms, and so on)
